### ISSUE TITLE
Skeletons Deal Too Much Damage to Gunmen

### ISSUE THREAD

**Issue by EresSirius** [Zicerite/Gavania-Project#73] opened 2018-08-04 16:23 UTC
Skeletons deal too much damage to Gunmen, often instantly killing them even if they have many more levels. For example, a level 255 gunman (with no armor) will survive with only 2 hearts when hit by a level 2 weak skeleton.

This was originally found by kohlth, so ask him if you have any questions.

**Comment by Zicerite** [comment] 2018-08-04 18:38
Skeletons are able to instantly kill all classes, and i haven't found the cause yet.
Still searching...

**Comment by Zicerite** [comment] 2018-08-06 08:32
The cause was from a multiplier issue. All other classes will be investigated.

**Closed by Zicerite** 2018-08-06 08:32 UTC
Labels: High Priority, bug
